### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by andywang7259** [flyerhzm/rfetion#15]
I, [2010-05-18T08:02:23.238618 #30410]  INFO -- : fetion login
I, [2010-05-18T08:02:24.954626 #30410]  INFO -- : fetion login success
I, [2010-05-18T08:02:24.954815 #30410]  INFO -- : fetion register
I, [2010-05-18T08:02:30.846979 #30410]  INFO -- : fetion pulse
I, [2010-05-18T08:02:33.269257 #30410]  INFO -- : fetion pulse success
I, [2010-05-18T08:02:34.229234 #30410]  INFO -- : fetion pulse
request_url: http://221.176.31.39/ht/sd.aspx?t=s&i=5, request_body: SIPP, sipc_response: SIP-C/4.0 421 Extension Required
Please use 'rfetion -h' to get more details

**Comment by flyerhzm** [comment]
It needs verification code, please use version before 0.5

**Comment by andywang7259** [comment]
thanks
