### ISSUE TITLE
Fetion::SipcException

### ISSUE THREAD

**Issue by incubus** [flyerhzm/rfetion#18]
Hello! I've tried latest gem and master from git:

$ Fetion.send_sms
fetion login
fetion login success
fetion register
fetion pulse
fetion pulse success
fetion pulse
fetion pulse success
fetion register success
fetion get contacts
fetion get contact info of uri:sip:xxx@fetion.com.cn;p=6197
fetion pulse
Fetion::SipcException: Fetion::SipcException
    from /home/incubus/workspace/test/vendor/plugins/rfetion/lib/rfetion/fetion.rb:439:in `curl_exec'

**Comment by flyerhzm** [comment]
Please add the option <code>:logger_level => Logger::DEBUG</code> to get debug information. If they are not helpful for you, you can paste them to me, I will try to fix it.

**Comment by incubus** [comment]
Hello! It works when my receivers list is empty. And breaks with a mobile number in the options[:receivers]. I can send a full log to you if you want. Thanks!

<args><contact uri="uri:sip:xxx@fetion.com.cn;p=6197" /></args>SIPP
response: #<Net::HTTPOK 200 OK readbody=true>
response body: SIP-C/4.0 200 OK
I: 5
Q: 1 S
L: 817

<results><topic-list event="RecommendGroupTopic" version="207" max-count="5"><topic title="飞信第一美女！" url="http://group.fetion.com.cn/topic/common/9061768/209529?c=[c:m161.com.cn]" create-date="2010-6-21 18:08:34" id="207" topic-type="1"  /><topic title="群主原创真人Q版像" url="http://group.fetion.com.cn/topic/common/31533037/209572?c=[c:m161.com.cn]" create-date="2010-6-21 18:07:54" id="206" topic-type="1"  /><topic title="【文学】三国之马" url="http://group.fetion.com.cn/topic/common/31069293/209628?c=[c:m161.com.cn]" create-date="2010-6-21 18:05:55" id="205" topic-type="1"  /><topic title="今年最易失恋星座" url="http://group.fetion.com.cn/topic/common/31424656/209718?c=[c:m161.com.cn]" create-date="2010-6-21 18:04:36" id="204" topic-type="1"  /></topic-list></results>SIPP
fetion curl exec complete
fetion pulse
fetion curl exec
url: http://221.176.31.39/ht/sd.aspx?t=s&i=10
body: SIPP
response: #<Net::HTTPOK 200 OK readbody=true>
response body: SIP-C/4.0 400 Bad Request
I: 6
Q: 1 S

SIPP
fetion curl exec complete
Fetion::SipcException: Fetion::SipcException
