### ISSUE TITLE
Fetion Error: Login failed.   rfetion -v = 0.4.7

### ISSUE THREAD

**Issue by andywang7259** [flyerhzm/rfetion#20]
以前还好好的，不知道最近一个月为什么就不能用了。报错为Fetion Error: Login failed.
请问该怎么解决呢？
谢谢您！

**Comment by flyerhzm** [comment]
飞信已经不再支持旧版本的接口，你可以尝试一下新版本的，不过我还没有完成

**Comment by andywang7259** [comment]
恩，谢谢您！您的很多代码写的都很挺不错的。
上次 使用了您的最新版本，不过因为飞信那边有验证码  后来改了低版本。最近一个月 低版本也不能用了。
我尝试用了  http://gist.github.com/498262    暂时能使用了。   如果您的写好了，再改用您的。  
感谢您提供这么好的应用～
