### ISSUE TITLE
能不能做为服务调用？

### ISSUE THREAD

**Issue by zbage** [flyerhzm/rfetion#6]
对于一个RAILS应用，能否做为服务调用，不用每次发信息都执行登陆，离线过程。

**Comment by zbage** [comment]
跟 http://github.com/yong/purple_ruby 类似

**Comment by flyerhzm** [comment]
你可以看一下源代码，我在README中写的都是Fetion的类方法，你可以参照这些类方法来调用实例方法，这样就不需要每次都登陆离线了。
