### ISSUE TITLE
列出所有好友的手机号

### ISSUE THREAD

**Issue by alvin2ye** [flyerhzm/rfetion#7]

**Comment by flyerhzm** [comment]
你可以调用下面的方法

<pre><code>
    fetion = Fetion.new
    fetion.logger_level = level
    fetion.mobile_no = mobile_no
    fetion.password = password
    fetion.login
    fetion.register
    fetion.get_buddy_list
    fetion.get_contacts_info
</code></pre>


<code>fetion.contacts</code> 就是所有的联系人信息
